SourceFile=open('pyton.txt','w')
f=input()
f=input()
f=f.split()
a=f[0].upper()
b=f[1].capitalize()
c='%s,%s' %(b,a)
d='{},{}'.format(a,b)
d.split()
e='!{0},{1}?'.format(a,b)
print(f,a,b,c,d,e,sep='<<<>>>', file=SourceFile)
